[tool.black]
target-version = ['py37']
include = '\.pyi?$'
exclude = '''
(
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.pytest_cache
  | \.tox
  | \.venv
  | \.vscode
  | venv
  | build
  | dist
)
'''

[tool.semantic_release]
branch = 'master'
version_source = 'tag'
version_variable = 'src/compiler/__init__.py:__version__'
commit_version_number = false
upload_to_pypi = false
