[tool.black]
target-version = ['py37']
include = '\.pyi?$'
exclude = '''
(
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.pytest_cache
  | \.tox
  | \.venv
  | \.vscode
  | venv
  | build
  | dist
)
'''
